spring.application.name=produtos-frontend
server.port=8080

# Configuração para servir arquivos estáticos
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
# Desabilitar funcionalidades não necessárias
spring.thymeleaf.enabled=false

# --- CONFIGURAÇÃO DO BANCO DE DADOS (POSTGRESQL RENDER) ---
# URL de conexão (com sslmode=require para conexões externas seguras)
spring.datasource.url=jdbc:postgresql://dpg-d85rv7reo5us73bj2mn0-a.virginia-postgres.render.com/atv17?sslmode=require

# Credenciais de acesso
spring.datasource.username=atv17_user
spring.datasource.password=6nmt1sCyzTh5cZvGlLDkBjB0nFJepxnM

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# update: Cria as tabelas se não existirem e atualiza a estrutura sem apagar os dados existentes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra as queries SQL no console (útil para desenvolvimento)
spring.jpa.show-sql=true